name: Mac Builds

# Overall ddbc should work on the last 10 minor compiler releases (same as Vibe.d) but for
# simplicity and speed of the CI most builds should be covered by Linux with the
# Windows and MacOS pipelines just testing with the last few compiler versions.

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.compiler }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.094.2
          - dmd-2.093.1
          - dmd-2.092.1
          - dmd-2.091.1
          - ldc-1.24.0 # eq to dmd v2.094.1
          - ldc-1.23.0 # eq to dmd v2.093.1
          - ldc-1.22.0 # eq to dmd v2.092.1
          - ldc-1.21.0 # eq to dmd v2.091.1
    steps:
      - uses: actions/checkout@v2

      - name: Install D ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install dependencies on Mac OSX
        run: brew bundle

      # - name: Upgrade dub dependencies
      #   uses: WebFreak001/dub-upgrade@v0.1

      - name: dub test with SQLite config
        run: dub test --config=SQLite
        
      - name: dub run with test config
        run: dub run --config=test
        
      - name: run the ddbctest project
        working-directory: example
        run: dub build --config=SQLite && ./ddbctest --connection=sqlite:ddbc-test.sqlite

      # cache
      # - uses: WebFreak001/dub-upgrade@v0.1
      #   with: { store: true }
